name: Build and Release EXE

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create release after build'
        required: false
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Verify config
      run: |
        python -c "import config; print('Config loaded successfully')"

    - name: Create version file
      id: version
      run: |
        $version = if ($env:GITHUB_REF -match "refs/tags/(.*)") { $matches[1] } else { "v1.0.$env:GITHUB_RUN_NUMBER" }
        $version | Out-File -FilePath "VERSION" -Encoding utf8 -NoNewline
        echo "VERSION=$version" >> $env:GITHUB_ENV
        echo "version=$version" >> $env:GITHUB_OUTPUT

    - name: Build executable
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY || 'GITHUB_BUILD_PLACEHOLDER' }}
      run: |
        python scripts/build.py

    - name: Copy version to dist
      run: |
        Copy-Item "VERSION" "dist/VERSION"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AJG-${{ steps.version.outputs.version }}
        path: |
          dist/AJG.exe
          dist/VERSION

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: AJG ${{ steps.version.outputs.version }}
        body: |
          🚀 **Nova versão do Sistema AJG - Assistência Judiciária Gratuita**

          ## 📥 Download
          - Baixe o arquivo `AJG.exe`
          - Execute direto no Windows (não precisa instalar)

          ## ⚙️ Configuração Necessária
          **IMPORTANTE:** Para usar o executável, você precisa configurar sua chave OpenRouter:
          1. Obtenha uma chave em: https://openrouter.ai/keys
          2. Edite o arquivo config.py (linha 57) antes de usar
          3. Ou use variável de ambiente: `set OPENROUTER_API_KEY=sua-chave`

          ## ✨ Atualizações
          - Build automático #${{ github.run_number }}
          - Gerado automaticamente do commit: ${{ github.sha }}
          - Sistema de auto-atualização integrado

          ---
          🤖 Build automatizado via GitHub Actions
        files: |
          dist/AJG.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}